site_name: 从零到精通：PyTorch 深度学习训练营
site_url: https://19z.github.io/pytorch-deep-learning/
site_description: 通过编写 PyTorch 代码，亲手学习重要的机器学习概念。

repo_url: https://github.com/19z/pytorch-deep-learning/
repo_name: 19z/pytorch_deep_learning

theme:
  name: material
  logo: assets/ztm-logo-and-pytorch-logo.png
  favicon: assets/ztm-logo-and-pytorch-logo.png
  features:
    - navigation.instant
    - navigation.top
  palette:
    primary: black

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - search
 - social

edit_uri: ""

nav:
  - 首页: 'index.md'
  - 00. PyTorch 入门: '00_pytorch_fundamentals.ipynb'
  - 01. PyTorch 机器学习工作流程: '01_pytorch_workflow.ipynb'
  - 02. PyTorch 神经网络分类: '02_pytorch_classification.ipynb'
  - 03. PyTorch 计算机视觉: '03_pytorch_computer_vision.ipynb'
  - 04. PyTorch 自定义数据集: '04_pytorch_custom_datasets.ipynb'
  - 05. PyTorch 模块化: '05_pytorch_going_modular.md'
  - 06. PyTorch 迁移学习: '06_pytorch_transfer_learning.ipynb'
  - 07. PyTorch 实验跟踪: '07_pytorch_experiment_tracking.ipynb'
  - 08. 使用 PyTorch 复现机器学习研究论文: '08_pytorch_paper_replicating.ipynb'
  - 09. 部署 PyTorch 机器学习模型: '09_pytorch_model_deployment.ipynb'
  - PyTorch 2 快速教程: 'pytorch_2_intro.ipynb'
  - PyTorch 额外资源: 'pytorch_extra_resources.md'
  - PyTorch 速查表: 'pytorch_cheatsheet.ipynb'
  - 三个最常见的 PyTorch 错误: 'pytorch_most_common_errors.ipynb'
  # - Test 00 as markdown: '00_pytorch_fundamentals.md'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mrdbourke
    - icon: fontawesome/brands/github
      link: https://github.com/mrdbourke/pytorch-deep-learning
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCr8O8l5cCX85Oem1d18EezQ
